
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[478] =
    {   0,
       14,   14,   30,   28,    1,    6,   20,   25,   28,   20,
       20,   26,   21,   20,   20,   20,   20,   20,   20,   12,
       12,   20,   20,   20,   20,    8,    8,    8,    8,    8,
       20,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   20,    1,   20,    0,    0,   17,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,   20,   14,   27,
        2,    0,   10,   12,   22,   22,   13,   15,   22,   22,
       20,   20,    8,    0,    8,    0,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    7,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    7,    8,
        8,    8,    8,    8,    8,    8,    8,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   23,    0,   23,    0,
        0,    0,    0,    4,    0,    0,    0,    0,    0,   16,
       24,    0,   13,   15,    0,    0,    2,   14,   11,    9,
       14,    8,    8,    0,    8,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    7,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    7,    0,   18,    0,    0,
       17,    0,    0,    0,    0,    0,    0,    5,    5,    5,
        0,    0,    0,    0,   16,    3,    0,    0,    0,    0,
        8,    8,    8,    8,    8,    8,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    0,
       23,    0,    0,    4,    0,    0,    5,    5,    0,    0,
        0,   19,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    0,   18,    0,    0,    4,    5,    0,    0,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    0,    0,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   22,   23,   22,   24,   25,   26,   27,   28,
       29,   30,   31,    1,   32,   32,   32,   32,   33,   34,
       35,   35,   35,   35,   35,   36,   35,   35,   35,   35,
       35,   37,   35,   35,   35,   35,   35,   38,   35,   35,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   35,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    5,    1,    1,    1,    1,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1,    7,    7,    6,    7,    6,    7,    7,    1,    4,
        1,    1,    7,    8,    8,    7,    7,    7,    9,    7,
        7,    7,    7,    6,    7,    8,    7,    7,    7,    8,
        7,    8,    7,    8,    7,    7,    7,    7,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[493] =
    {   0,
        0,    0,  927,  928,  924,  928,  896,   70,   29,  895,
       66,   69,  928,  894,   67,  928,   64,   79,   94,  108,
      159,  896,   56,  892,   59,    0,  170,    0,    0,  915,
      890,   51,   56,  152,  150,   81,  156,  861,   66,  860,
      853,  157,   59,   58,  867,  167,  164,   64,   82,  175,
      857,  157,  911,  928,  225,  907,  928,  263,  863,  179,
      185,  858,  849,  852,  898,  928,  231,  894,  310,  893,
        0,  224,  212,    0,  349,  332,    0,    0,  386,  130,
      875,  874,    0,  368,  243,  892,  849,  853,  844,  836,
      835,  839,  847,  161,  850,  849,  208,  206,  829,  835,

      829,  826,   24,  834,  830,  826,  833,  822,    0,  199,
      827,  820,  826,  815,   88,  825,  830,  834,  202,  831,
      252,  818,  134,  223,  822,  818,  210,  206,  814,  147,
      819,  810,  230,  818,  816,  807,  928,  296,  269,  817,
      229,  818,  804,  238,  817,  806,  817,  813,  850,  928,
      849,  423,  928,  928,  845,  288,    0,  326,    0,  219,
      288,    0,    0,  337,  806,  812,  797,  269,  799,  808,
      803,  804,  789,  787,  334,  789,  338,  792,  801,  796,
      798,  798,  793,  785,  232,  791,  777,  793,  788,  778,
      782,  783,  788,  783,  764,  786,  774,  767,  778,  761,

      762,  769,  770,  765,  757,  756,  758,  761,  768,  753,
      751,  751,  754,  750,  258,  762,  761,  751,  755,  750,
      743,  757,  759,  758,  747,  757,  376,  928,  446,  356,
      928,  796,  746,  748,  748,  743,  737,    0,  745,  745,
      737,  742,  739,  740,  928,  928,  410,  412,  453,  417,
      731,  738,  729,  724,  730,  731,  297,  720,  715,  731,
      726,  723,  728,  713,  722,  711,  709,  709,  716,  714,
      716,  707,  706,  717,  702,  707,  706,  716,  699,  713,
      710,  699,  712,  696,  710,  705,  700,  690,  688,  697,
      688,  685,  698,  688,  692,  697,  696,  687,  696,  674,

      407,  682,  687,  686,  672,  672,  673,  684,  683,  434,
      420,  435,  674,    0,  680,  668,  678,  678,  662,  669,
      674,  928,  319,  663,  674,  697,  699,  675,  673,  654,
      667,  656,  424,  657,  645,  657,  662,  661,  656,  661,
      644,  649,  657,  655,  648,  643,  652,  640,  636,  635,
      634,  649,  648,  631,  644,  631,  634,  642,  639,  641,
      624,  634,  640,  636,  634,  634,  636,  623,  634,  625,
      633,  616,  448,  928,  671,  625,    0,  623,  624,  626,
      608,  619,  624,  623,  603,  612,  600,  608,  599,  614,
      232,  603,  595,  599,  594,  609,  602,  605,  608,  593,

      590,  592,  600,  585,  598,  585,  596,  600,  580,  598,
      591,  584,  590,  583,  582,  573,  460,  586,  569,  568,
      567,  558,  567,  569,  568,  544,  546,  549,  543,  546,
      526,  533,  499,  449,  459,  445,  446,  442,  368,  453,
      445,  450,  450,  448,  438,  431,  435,  427,  423,  438,
      435,  435,  420,  417,  427,  413,  407,  424,  381,  367,
      366,  378,  356,  340,  347,  304,  305,  276,  277,  257,
      256,  242,  149,  143,   77,   28,  928,  510,  519,  523,
      532,  541,  550,  559,  568,  577,  586,  590,  599,  607,
      616,  624

    } ;

static const flex_int16_t yy_def[493] =
    {   0,
      477,    1,  477,  477,  477,  477,  477,  478,  477,  477,
      477,  479,  477,  477,  477,  477,  477,  477,  477,  477,
       20,  477,  477,  477,  477,  480,  480,  480,  480,  480,
      477,  480,  480,  480,  480,   27,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  477,  477,  477,  478,  481,  477,  481,  477,  477,
      477,  477,  477,  477,  482,  477,  482,  477,  477,  483,
      484,  477,   20,   21,   21,   75,   75,   75,   75,   75,
      477,  477,  480,  477,   27,  477,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  477,  485,  486,  477,
      477,  477,  477,  487,  477,  477,  477,  477,  482,  477,
      477,  477,  477,  477,  483,  483,  484,   76,   79,   75,
      488,  480,  480,  489,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  485,  477,  481,  486,
      477,  490,  477,  477,  477,  477,  477,  487,  487,  487,
      477,  477,  477,  477,  477,  477,  489,  489,  489,  477,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  485,
      491,  491,  477,  487,  477,  477,  487,  487,  477,  477,
      477,  477,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  491,  477,  492,  477,  487,  487,  477,  477,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  491,  477,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,    0,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477

    } ;

static const flex_int16_t yy_nxt[1001] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   13,   23,   24,   25,
       16,   26,   27,   28,   26,   29,   30,   26,   13,    4,
       13,   31,   26,   32,   33,   34,   35,   36,   37,   38,
       26,   39,   26,   40,   41,   42,   43,   44,   26,   45,
       46,   47,   48,   49,   50,   51,   26,   26,   13,   52,
       13,   16,   56,   54,   57,   59,   60,   66,   54,   54,
       61,  185,   62,   81,   54,  186,   63,   54,   82,  109,
       54,   64,   54,   68,   54,   54,   69,   69,   69,   69,

       69,   69,   69,   69,   87,   70,   88,   91,   67,   58,
       71,   89,   92,   90,  109,   93,  117,  119,  118,  130,
      120,  110,   54,   72,  131,   73,   73,   73,   73,   73,
       73,   74,   74,  132,  101,  195,  102,  476,  133,   75,
       76,   77,   75,   78,   75,   79,  103,  160,  160,  196,
       75,   75,   80,   75,   75,   76,   77,   75,   75,   75,
       75,   78,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   79,   75,   75,   74,   74,   74,   74,
       74,   74,   84,  208,   84,   54,  475,   85,   85,   85,
       85,   85,   85,   85,   85,   94,   75,   98,  218,  104,

      113,  209,   95,   75,  114,   96,   99,  219,   97,  105,
      109,  126,  106,  115,  127,  107,  100,  122,  123,  116,
      134,  171,  172,  128,   75,  135,   54,   56,  124,   57,
      129,  125,  141,  144,  142,   65,  160,  160,  143,  151,
      145,   69,   69,   69,   69,   69,   69,   69,   69,   75,
      175,  178,  191,  200,  179,  477,   75,  477,  201,  180,
      109,  214,  176,  177,   58,  138,  210,  139,  216,  215,
       65,   55,  109,  231,   65,   65,  162,   75,  163,   65,
      234,  222,  211,  223,  239,  271,   65,  474,  272,  235,
       65,  162,   65,  240,   65,  425,  163,  426,   56,  156,

      228,  203,   55,  204,  246,  299,   55,   55,  232,  109,
      205,   55,  253,  206,  300,  326,  473,  327,   55,  472,
      328,  153,   55,  154,   55,  254,   55,   69,   69,   69,
       69,   69,   69,   69,   69,  229,  153,  109,  477,  248,
      477,  154,  152,  153,   84,  154,   84,  249,  471,  158,
      158,  158,  158,  158,  158,  158,  158,  152,  153,   77,
      231,   78,  381,  154,  477,  109,   75,   75,   75,   75,
       75,   75,   75,   75,   77,  382,  250,  259,   56,   78,
      228,   75,   75,  263,   75,  161,  161,  161,  161,  161,
      161,  161,  161,  260,  470,  232,   75,   75,  264,  265,

      261,  469,   75,  159,  159,  159,  159,  159,  159,  159,
      159,  454,  248,  455,  248,  229,  468,  159,  159,  159,
      249,  247,  249,  467,  374,  247,  466,  465,  464,  159,
      159,  159,  159,  159,  159,   84,   56,   84,  228,  374,
      161,  161,  161,  161,  161,  161,  161,  161,  310,  250,
      311,  250,  374,  365,  227,  248,  247,  322,  366,  375,
      247,  247,  367,  249,  374,  247,  390,  463,  109,  462,
      461,  391,  247,  229,  375,  392,  247,  460,  247,  459,
      247,  109,  109,  458,  109,  227,  109,  375,  109,  227,
      227,  457,  250,  109,  227,  109,  109,  109,  456,  375,

      109,  227,  109,  453,  109,  227,  452,  227,  109,  227,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   83,   83,
       83,   83,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  157,
      109,  157,  157,  157,  157,  157,  157,  157,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  230,  451,  230,
      230,  230,  230,  230,  230,  230,  238,  109,  450,  238,
      109,  238,  238,  238,  238,  161,  109,  449,  161,  247,

      247,  448,  247,  247,  247,  247,  247,  247,  230,  230,
      230,  447,  446,  109,  230,  230,  373,  445,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  109,  109,
      109,  373,  373,  314,  109,  444,  109,  443,  442,  109,
      441,  440,  439,  438,  437,  436,  435,  109,  434,  109,
      433,  432,  109,  431,  430,  109,  429,  428,  427,  424,
      109,  423,  422,  421,  109,  420,  419,  109,  109,  314,
      418,  377,  314,  417,  109,  416,  415,  414,  413,  412,
      109,  411,  410,  409,  109,  109,  408,  109,  109,  109,
      407,  406,  405,  109,  404,  403,  402,  401,  109,  400,

      399,  398,  109,  109,  109,  109,  397,  396,  109,  109,
      395,  394,  393,  389,  388,  387,  386,  385,  384,  383,
      109,  109,  314,  380,  379,  378,  377,  314,  314,  376,
      372,  109,  371,  370,  369,  109,  368,  109,  109,  364,
      363,  362,  361,  360,  359,  358,  109,  357,  356,  355,
      354,  353,  352,  351,  109,  350,  349,  348,  347,  346,
      345,  344,  343,  109,  109,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  109,  331,  330,  329,
      109,  109,  109,  109,  325,  324,  323,  321,  320,  314,
      319,  318,  317,  316,  315,  314,  314,  313,  312,  309,

      308,  307,  306,  109,  305,  304,  303,  302,  301,  109,
      109,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  109,  277,  109,  276,  275,  274,  273,  109,
      109,  270,  269,  268,  267,  266,  262,  258,  257,  256,
      109,  255,  109,  109,  252,  251,  156,  245,   66,  244,
      243,  242,  241,  237,  236,  233,  226,  225,  224,  221,
      220,  217,  213,  212,  207,  202,  199,  198,  197,  109,
      194,  193,  192,  190,  189,  109,  188,  187,  184,  183,
      182,  181,  174,  173,  170,  169,  168,  167,  109,  166,

      165,  164,   54,   54,  156,   54,  150,  148,  147,  146,
      140,  137,   53,  136,  121,  112,  111,  108,   54,   86,
       54,   54,   54,   54,   54,   53,  477,    3,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477

    } ;

static const flex_int16_t yy_chk[1001] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,   11,    8,    9,    9,   12,   17,   15,
        9,  103,    9,   23,   23,  103,    9,   25,   25,  476,
       18,    9,   17,   17,   11,   15,   18,   18,   18,   18,

       18,   18,   18,   18,   32,   19,   32,   33,   12,    8,
       19,   32,   33,   32,   39,   33,   43,   44,   43,   48,
       44,   39,   19,   20,   48,   20,   20,   20,   20,   20,
       20,   20,   20,   49,   36,  115,   36,  475,   49,   20,
       20,   20,   20,   20,   20,   20,   36,   80,   80,  115,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   21,   21,   21,   21,
       21,   21,   27,  123,   27,   52,  474,   27,   27,   27,
       27,   27,   27,   27,   27,   34,   21,   35,  130,   37,

       42,  123,   34,   21,   42,   34,   35,  130,   34,   37,
      473,   47,   37,   42,   47,   37,   35,   46,   46,   42,
       50,   94,   94,   47,   21,   50,   52,   55,   46,   55,
       47,   46,   60,   61,   60,   67,  160,  160,   60,   67,
       61,   72,   72,   72,   72,   72,   72,   72,   72,   73,
       97,   98,  110,  119,   98,   85,   73,   85,  119,   98,
      110,  127,   97,   97,   55,   58,  124,   58,  128,  127,
       67,   58,  128,  139,   67,   67,   85,   73,   85,   67,
      141,  133,  124,  133,  144,  185,   67,  472,  185,  141,
       67,   85,   67,  144,   67,  391,   85,  391,  138,  156,

      138,  121,   58,  121,  156,  215,   58,   58,  139,  471,
      121,   58,  168,  121,  215,  257,  470,  257,   58,  469,
      257,  161,   58,  161,   58,  168,   58,   69,   69,   69,
       69,   69,   69,   69,   69,  138,  161,  468,  158,  164,
      158,  161,   69,   69,   76,   69,   76,  164,  467,   76,
       76,   76,   76,   76,   76,   76,   76,   69,   69,  158,
      230,  158,  323,   69,   75,  466,   75,   75,   75,   75,
       75,   75,   75,   75,  158,  323,  164,  175,  227,  158,
      227,   75,   75,  177,   75,   84,   84,   84,   84,   84,
       84,   84,   84,  175,  465,  230,   75,   75,  177,  177,

      175,  464,   75,   79,   79,   79,   79,   79,   79,   79,
       79,  439,  247,  439,  248,  227,  463,   79,   79,   79,
      247,  250,  248,  462,  311,  250,  461,  460,  459,   79,
       79,   79,   79,   79,   79,  152,  310,  152,  310,  312,
      152,  152,  152,  152,  152,  152,  152,  152,  229,  247,
      229,  248,  373,  301,  229,  249,  250,  249,  301,  311,
      250,  250,  301,  249,  417,  250,  333,  458,  457,  456,
      455,  333,  250,  310,  312,  333,  250,  454,  250,  453,
      250,  452,  451,  450,  449,  229,  448,  373,  447,  229,
      229,  446,  249,  445,  229,  444,  443,  442,  441,  417,

      440,  229,  438,  437,  436,  229,  435,  229,  434,  229,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  480,  480,
      480,  480,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  484,
      433,  484,  484,  484,  484,  484,  484,  484,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  486,  432,  486,
      486,  486,  486,  486,  486,  486,  487,  431,  430,  487,
      429,  487,  487,  487,  487,  488,  428,  427,  488,  489,

      489,  426,  489,  489,  489,  489,  489,  489,  490,  490,
      490,  425,  424,  423,  490,  490,  491,  422,  491,  491,
      491,  491,  491,  491,  491,  492,  492,  492,  421,  420,
      419,  492,  492,  418,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  376,  375,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,

      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  321,  320,  319,  318,  317,  316,  315,  313,
      309,  308,  307,  306,  305,  304,  303,  302,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  256,  255,  254,  253,  252,  251,  244,  243,  242,
      241,  240,  239,  237,  236,  235,  234,  233,  232,  226,

      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  184,
      183,  182,  181,  180,  179,  178,  176,  174,  173,  172,
      171,  170,  169,  167,  166,  165,  155,  151,  149,  148,
      147,  146,  145,  143,  142,  140,  136,  135,  134,  132,
      131,  129,  126,  125,  122,  120,  118,  117,  116,  114,
      113,  112,  111,  108,  107,  106,  105,  104,  102,  101,
      100,   99,   96,   95,   93,   92,   91,   90,   89,   88,

       87,   86,   82,   81,   70,   68,   65,   64,   63,   62,
       59,   56,   53,   51,   45,   41,   40,   38,   31,   30,
       24,   22,   14,   10,    7,    5,    3,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <iostream>
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include <cstring>

// #define here std::cout << "HERE" << std::endl;

using namespace std;

#define DEBUGMODE 0 // 1 to show debug messages
#define SHOWERRORS 1 // 1 to show errors in error.txt 


#define TESTMODE 0
/*
1- String and Char Testing
2- Identifier Testing
*/

// Token classes
enum class TokenClass {
    KEYWORD,
    IDENTIFIER,
    LITERAL, // 2-9
    DECIMAL,
    BINARY,
    OCTAL,
    HEX,
    DOUBLE,
    CHAR,
    STRING, 
    PUNCTUATION, // 10
    OPERATOR, // 11
    UNKNOWN, // 12
    MULTI_LINE_STRING,
    MULTI_LINE_STRING_RAW,
    FLOAT, // 15
    LONG_DOUBLE // 16
};

char* tokenToString(TokenClass token) {
    int tokenValue = static_cast<int>(token);
    switch(tokenValue) {
        case 0: return "KEYWORD";
        case 1: return "IDENTIFIER";
        case 2: return "LITERAL";
        case 3: return "DECIMAL LITERAL";
        case 4: return "BINARY LITERAL";
        case 5: return "OCTAL LITERAL";
        case 6: return "HEX LITERAL";
        case 7: return "DOUBLE LITERAL";
        case 8: return "CHAR LITERAL";
        case 9: return "STRING LITERAL";
        case 10: return "PUNCTUATION";
        case 11: return "OPERATOR";
        case 12: return "UNKNOWN";
        case 13: return "MULTI_LINE_STRING";
        case 14: return "MULTI_LINE_STRING_RAW";
        case 15: return "FLOAT LIETRAL";
        case 16: return "LONG_DOUBLE LIETRAL";
        default: return "INVALID TOKEN CLASS";
    }
}


FILE *output_file;
FILE *error_file;
int line_number = 1;


// ----------- LEXER TABLE -------------------
// Define the width of each column in the lexer table 
vector<int> columnWidths = {10, 30, 50, 35};
int errorWidth = 30;


void printLexerTableSeparator() {
    fprintf(output_file, "+");
    for (int i = 0; i < columnWidths.size(); i++) {
        for (int j = 0; j < columnWidths[i]+1; j++) {
            fprintf(output_file, "-");
        }
        fprintf(output_file, "+");
    }
    fprintf(output_file, "\n");
}

void printLexerTableHeader() {
    printLexerTableSeparator();
    fprintf(output_file, "| %-*s| %-*s| %-*s| %-*s|\n", columnWidths[0], "Line No", columnWidths[1], "Token", columnWidths[2], "Lexeme", columnWidths[3], "More Info");
    printLexerTableSeparator();
}

void printLexerTable(int lineNo, char *token, char *lexeme, string moreInfo) {

    // Calculate the number of spaces to add to each column
    fprintf(output_file,"| %-*d| %-*s| %-*s| %-*s|\n", columnWidths[0], lineNo, columnWidths[1], token, columnWidths[2], lexeme, columnWidths[3], moreInfo.c_str());
    
    // Print the table separator
    printLexerTableSeparator();
}

void printLexerTable(int lineNo, char *token, char *lexeme) {
    printLexerTable(lineNo, token, lexeme, "N/A");
}


//  TOKENS----------------------------------------------

std::map<string,string> KeywordInfo;
std::map<string,string> OperatorInfo;
std::map<string,string> PunctuationInfo;

// Forward declarations of token handlers
void handleToken(TokenClass token, char *lexeme);
void handleKeyword(char *lexeme);
void handleIdentifier(char *lexeme);
void handleLiteral(TokenClass token, char *lexeme);
void handleMultiLineString(char *lexeme);
void handleMultiLineStringRAW(char *lexeme);
void handlePunctuation(char *lexeme);
void handleOperator(char *lexeme);

void handleUnknown(char *lexeme);


// Base Token Handler
void handleToken(TokenClass token, char *lexeme) {
    
    if(TESTMODE == 1){
        // Testing for string and char only
        int tokenValue = static_cast<int>(token);
        if(tokenValue != 8 && tokenValue !=9 && tokenValue != 13 && tokenValue != 14){
            return;
        }
    }

    if(TESTMODE == 2){
        // Testing for identifier only
        if(token != TokenClass::IDENTIFIER){
            return;
        }
    }


    int tokenValue = static_cast<int>(token);

    if(tokenValue == 0) {
        handleKeyword(lexeme);
    }
    else if(tokenValue == 1) {
        handleIdentifier(lexeme);
    }
    else if(tokenValue >= 2 && tokenValue <= 9 || tokenValue == 15 || tokenValue == 16) {
        handleLiteral(token, lexeme);
    }
    else if(tokenValue == 10) {
        handlePunctuation(lexeme);
    }
    else if(tokenValue == 11) {
        handleOperator(lexeme);
    }
    else if(tokenValue == 12) {
        printLexerTable(line_number, "UNKNOWN", lexeme);
    }
    else if(tokenValue == 13) {
        handleMultiLineString(lexeme);
    }
    else if(tokenValue == 14) {
        handleMultiLineStringRAW(lexeme);
    }
    else{
        printLexerTable(line_number, "Something Wrong", lexeme);
    }
}

//------------ KEYWORDS

// Adding more info to the keyword
void InitializeKeywordMap(){
    // KeywordInfo["alignas"] = "Alignment specifier";
    KeywordInfo["nullptr"] = "Pointer literal";
    KeywordInfo["true"] = "Boolean literal";
    KeywordInfo["false"] = "Boolean literal";

    KeywordInfo["new"] = "OP - P3, R-L";
    KeywordInfo["delete"] = "OP - P3, R-L";
    KeywordInfo["sizeof"] = "OP - P3, R-L";

    KeywordInfo["alignas"] = "Alignment specifier";
    KeywordInfo["int"] = "Data type";
    KeywordInfo["char"] = "Data type";
    KeywordInfo["float"] = "Data type";
    KeywordInfo["double"] = "Data type";
    KeywordInfo["void"] = "Data type";
    KeywordInfo["bool"] = "Data type";
    KeywordInfo["short"] = "Data type";
    KeywordInfo["long"] = "Data type";
    KeywordInfo["signed"] = "Data type";
    KeywordInfo["unsigned"] = "Data type";
    KeywordInfo["auto"] = "Type specifier";
    KeywordInfo["const"] = "Type qualifier";
    KeywordInfo["volatile"] = "Type qualifier";

    KeywordInfo["if"] = "Conditional statement";
    KeywordInfo["else"] = "Conditional statement";
    KeywordInfo["switch"] = "Conditional statement";
    KeywordInfo["case"] = "Conditional statement";
    KeywordInfo["default"] = "Conditional statement";
    
    KeywordInfo["for"] = "Loop statement";
    KeywordInfo["while"] = "Loop statement";
    KeywordInfo["do"] = "Loop statement";
    KeywordInfo["break"] = "Loop control statement";
    KeywordInfo["continue"] = "Loop control statement";

    KeywordInfo["return"] = "Function return statement";

}

void handleKeyword(char *lexeme) {
    string key = lexeme;
    if(KeywordInfo.find(key) != KeywordInfo.end()) {
        printLexerTable(line_number, "KEYWORD", lexeme, KeywordInfo[key]);
    }
    else{
        printLexerTable(line_number, "KEYWORD", lexeme);
    }
}

//------------- IDENTIFIERS
void handleIdentifier(char *lexeme) {

    if(strcmp(lexeme, "main") == 0){
        printLexerTable(line_number, "IDENTIFIER", lexeme, "Special Funciton Name");
        return;
    }

    printLexerTable(line_number, "IDENTIFIER", lexeme);
}


//------------- LITERALS
void handleLiteral(TokenClass token, char *lexeme) {
    // We just need to print the token and lexeme
    char* tokenString = tokenToString(token);

    printLexerTable(line_number, tokenString, lexeme);
}

//------------- MULTI LINE STRING
void handleMultiLineStringRAW(char *lexeme) {
    // we will remove the \n from the lexeme
    string lexemeString = lexeme;
    string newLexeme;
    int currLineNo = line_number;

    for(int i = 0; i < lexemeString.size(); i++){
        if(i==0 | i==2 | i==lexemeString.size()-2){
            continue;
        }
        if(lexemeString[i] == '\n'){
            line_number++;
        }
        else{
            newLexeme += lexemeString[i];
        }
    }

    char* newLexemeChar = (char*)newLexeme.c_str();
    printLexerTable(currLineNo, "STRING LITERAL", newLexemeChar,"RAW Multi Line String");
}

void handleMultiLineString(char *lexeme) {
    // we will remove the \n from the lexeme &
    string lexemeString = lexeme;
    string newLexeme;
    int currLineNo = line_number;
    
    for(int i = 0; i < lexemeString.size(); i++){
        if(lexemeString[i] == '\\' && lexemeString[i+1] == '\n'){
            line_number++;
            i++;
        }
        else{
            newLexeme += lexemeString[i];
        }
    }
    char* newLexemeChar = (char*)newLexeme.c_str();
    printLexerTable(currLineNo, "STRING LITERAL", newLexemeChar,"Multi Line String");
}

//---------- PUNCTUATION
void InitializePunctuationMap(){
    PunctuationInfo["("] = "Left Parenthesis";
    PunctuationInfo[")"] = "Right Parenthesis";
    PunctuationInfo["["] = "Left Square Bracket";
    PunctuationInfo["]"] = "Right Square Bracket";
    PunctuationInfo["{"] = "Left Curly Brace";
    PunctuationInfo["}"] = "Right Curly Brace";
    PunctuationInfo[";"] = "Semi-colon";
}

void handlePunctuation(char *lexeme) {
    string key = lexeme;
    if(PunctuationInfo.find(key) != PunctuationInfo.end()) {
        printLexerTable(line_number, "PUNCTUATION", lexeme, PunctuationInfo[key]);
    }
    else{
        printLexerTable(line_number, "PUNCTUATION", lexeme);
    }
}


//---------- OPERATORS -------------------------------
void InitializeOperatorMap(){
    //// We will be categorizing on basis of Precedence and Associativity
    OperatorInfo["::"] = "P1, L-R";

    OperatorInfo["++"] = "Depends on PostFix or Prefix"; // Postfix
    OperatorInfo["--"] = "Depends on PostFix or Prefix"; // Postfix

    OperatorInfo["~"] = "Bitwise NOT"; // Bitwise NOT (one's complement)
    OperatorInfo["!"] = "Logical NOT"; // Unary logical NOT
    OperatorInfo["-"] = "Can be \"Uniary Negation\" or \"Subtraction"; // Unary minus
    OperatorInfo["+"] = "Can be \"Uniary Plus\" or \"Addition\""; // Unary plus
    OperatorInfo["&"] = "Can be \"Address-of\" or \"Bitwise ANd\""; // Address-of
    OperatorInfo["*"] = "It can be \"Indirection\" or \"Multiplication\""; // Dereference or multiplication
    // Keyword (sizeof, new, delete) are also operators
    OperatorInfo["/"] = "Division";
    OperatorInfo["\%"] = "Modulus"; // --------__TODO

    OperatorInfo["<<"] = "Left Shift";
    OperatorInfo[">>"] = "Right Shift";

    OperatorInfo["<"] = "Less than";
    OperatorInfo[">"] = "Greater than";
    OperatorInfo["<="] = "Less than or equal to";
    OperatorInfo[">="] = "Greater than or equal to";

    OperatorInfo["=="] = "Equal to";
    OperatorInfo["!="] = "Not equal to";

    // OperatorInfo["&"] = "Bitwise AND";

    OperatorInfo["^"] = "Bitwise exclusive OR";

    // OperatorInfo["|"] = "Bitwise OR";

    OperatorInfo["&&"] = "Logical AND";

    OperatorInfo["||"] = "Logical OR";

    OperatorInfo["?"] = "Conditional Operator (Ternary)";
    OperatorInfo[":"] = "Conditional Operator (Ternary)";

    OperatorInfo["="] = "Assignment Operator";
    OperatorInfo["*="] = "MUL Assignment Operator";
    OperatorInfo["/="] = "DIV Assignment Operator";
    OperatorInfo["%="] = "MOD Assignment Operator";
    OperatorInfo["+="] = "ADD Assignment Operator";
    OperatorInfo["-="] = "SUB Assignment Operator";
    OperatorInfo["<<="] = "Left Shift Assignment Operator";
    OperatorInfo[">>="] = "Right Shift Assignment Operator";
    OperatorInfo["&="] = "Bitwise AND Assignment Operator";
    OperatorInfo["^="] = "Bitwise XOR Assignment Operator";
    OperatorInfo["|="] = "Bitwise OR Assignment Operator";

    OperatorInfo[","] = "Comma Operator";
}

void handleOperator(char *lexeme) {
    string key = lexeme;
    if(OperatorInfo.find(key) != OperatorInfo.end()) {
        printLexerTable(line_number, "OPERATOR", lexeme, OperatorInfo[key]);
    }
    else{
        printLexerTable(line_number, "OPERATOR", lexeme);
    }
}

//---------- UNKNOWN
void handleUnknown(char *lexeme) {
    printLexerTable(line_number, "UNKNOWN", lexeme);
}


//----------------------------------------------ERRORS----------------------------------------------

void handleError(char *lexeme, char *error) {
    // check if error mode
    if(!SHOWERRORS){
        return;
    }
    fprintf(error_file, "L.no: %d | ERROR: %-*s| Lexeme: %s\n", line_number, errorWidth, error, lexeme);
}


#line 1229 "lex.yy.c"
/* Definitions */
/* Regular Expressions */
/* NOT in USE */
#line 1233 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 458 "lexer.l"


#line 1453 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 478 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 928 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 460 "lexer.l"
{ /* Ignore whitespace */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 461 "lexer.l"
{ DEBUGMODE ? fprintf(output_file, "COMMENT1: %s\n", yytext) : NULL; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 462 "lexer.l"
{ DEBUGMODE ? fprintf(output_file, "COMMENT2: %s\n", yytext) : NULL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 463 "lexer.l"
{  }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 464 "lexer.l"
{ printLexerTable(line_number, "PREPROCESSOR", yytext); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 466 "lexer.l"
{ line_number++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 468 "lexer.l"
{ handleToken(TokenClass::KEYWORD, yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 470 "lexer.l"
{ handleToken(TokenClass::IDENTIFIER, yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 472 "lexer.l"
{ handleToken(TokenClass::BINARY, yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 473 "lexer.l"
{ handleToken(TokenClass::OCTAL, yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 474 "lexer.l"
{ handleToken(TokenClass::HEX, yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 475 "lexer.l"
{ handleToken(TokenClass::DECIMAL, yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 478 "lexer.l"
{ handleToken(TokenClass::FLOAT, yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 479 "lexer.l"
{ handleToken(TokenClass::DOUBLE, yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 480 "lexer.l"
{ handleToken(TokenClass::LONG_DOUBLE, yytext); }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 481 "lexer.l"
{ handleToken(TokenClass::CHAR, yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 484 "lexer.l"
{ handleToken(TokenClass::STRING, yytext); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 485 "lexer.l"
{ handleToken(TokenClass::MULTI_LINE_STRING, yytext); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 486 "lexer.l"
{ handleToken(TokenClass::MULTI_LINE_STRING_RAW, yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 490 "lexer.l"
{ handleToken(TokenClass::OPERATOR, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 492 "lexer.l"
{ handleToken(TokenClass::PUNCTUATION, yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 494 "lexer.l"
{ handleError(yytext, "INVALID Identifier."); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 495 "lexer.l"
{ handleError(yytext, "INVALID string literal."); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 496 "lexer.l"
{ handleError(yytext, "INVALID character literal."); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 498 "lexer.l"
{ handleError(yytext, "Unclosed string literal in Same Line."); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 499 "lexer.l"
{ handleError(yytext, "Unclosed character literal."); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 500 "lexer.l"
{ handleError(yytext, "Unclosed comment."); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 503 "lexer.l"
{ handleUnknown(yytext); handleError(yytext, "Unknown token."); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 505 "lexer.l"
ECHO;
	YY_BREAK
#line 1662 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 478 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 478 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 477);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 505 "lexer.l"



int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input_file>\n", argv[0]);
        return 1;
    }

    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror("Error opening input file");
        return 1;
    }

    string outputFileName = "output.txt";
    string errorFileName = "error.txt";

    // we will open the output file in write mode with the name of input file
    stringstream ss(argv[1]);
    string input_name;
    getline(ss, input_name, '.');
    outputFileName = input_name + "_output.txt";
    errorFileName = input_name + "_error.txt";

    output_file = fopen(outputFileName.c_str(), "w");
    if (!output_file) {
        perror("Error opening output file");
        return 1;
    }

    if(SHOWERRORS){
    error_file = fopen(errorFileName.c_str(), "w");
    if (!error_file) {
        perror("Error opening error file");
        return 1;
    }
    }


    InitializeKeywordMap();
    InitializeOperatorMap();
    InitializePunctuationMap();
        
    // Print the header of the lexer table
    printLexerTableHeader();


    yylex();  // Start lexical analysis


    // Close the FILE pointers
    fclose(yyin);
    fclose(output_file);
    if(SHOWERRORS){
        fclose(error_file);
    }

    // Memory cleanup
    KeywordInfo.clear();
    OperatorInfo.clear();
    PunctuationInfo.clear();
    

    return 0;
}
