#ifndef TOKENS_H
#define TOKENS_H

#define KEYWORD 1
#define IDENTIFIER 2
#define INTEGER_CONSTANT 3
#define FLOATING_CONSTANT 4
#define STRING_LITERAL 5
#define CHARACTER_CONSTANT 6
#define OPERATOR 7
#define PUNCTUATOR 8
#define COMMENT 9
#define PREPROCESSOR 10
#define UNKNOWN 11

#endif
