#include <iostream>
#include "parser.tab.h"  // Include the BISON-generated header

extern int yyparse();  // Function generated by BISON
extern FILE *yyin;     // File pointer for input

extern int DEBUGMODE;  // Debug mode flag | 
// // 0: No debug, 1: Error, 2: Warning, 3: Info, 4: Debug

int main(int argc, char **argv) {
    // Check if a file is provided as an argument

    // Check for debug flag and input file
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <input_file> [-d<debug_mode>]\n";
        // Optional debug mode flag
        return 1;
    }

    // The DEBUGMODE flag is set to 0 by default and can be absent
    if(argc == 3) {
        if(argv[2][0] == '-' && argv[2][1] == 'd') {
            int debugMode = argv[2][2] - '0';
            if(debugMode >= 0 && debugMode <= 2) {
                DEBUGMODE = debugMode;
            } else {
                std::cerr << "Error: Invalid debug mode\n";
                return 1;
            }
        }
    }

    // Open the input file
    yyin = fopen(argv[1], "r");
    if (!yyin) {
        std::cerr << "Error: Unable to open the input file\n";
        return 1;
    }
    
    // Redirect output to files instead of stdout and stderr
    std::string outputFileName = "output.txt";
    freopen(outputFileName.c_str(), "w", stdout);

    std::cout << "..........Starting parsing..........\n";
    yyparse();  // Call BISON's parser
    std::cout << "..........Parsing complete..........\n";

    if (yyin) fclose(yyin);  // Close the input file if opened
    return 0;
}
